### ISSUE TITLE
'sudo: unable to resolve host'...

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/sandboxlib#10]
I'm seeing this on some systems. for example:

```
sudo: unable to resolve host armadaxp
```

things seem to work in spite of this. can the message be turned off somehow,  or is it a sign of a problem?

**Comment by richardmaw-codethink** [comment]
You shouldn't be getting this in a normal Baserock system, since we should be using the nss_myhostname module provided by systemd, which ensures that your local hostname is _always_ resolvable.

I think this error message comes from the fact that sudo can be LDAP authenticated, so the user and the hostname may be required information for deciding whether sudo is allowed.

I don't know of a way to suppress the message, but if it's a normal Baserock system you can check whether /etc/nsswitch.conf contains myhostname. If it does not I think you can copy a good version from /usr/share/factory/etc/nsswitch.conf (provided by systemd).

If for some reason you _need_ it to be a non-standard Baserock system, you should be able to add your hostname to /etc/hosts. Googling for "sudo: unable to resolve host" brings up this solution in my google-bubble.

**Comment by ghost** [comment]
There's nothing in the sandboxlib code that calls `sudo`, so this can't be a sandboxlib issue. Please reopen if I'm missing something, but I imagine this is coming from the code in YBD which creates `/dev/null` using `sudo`.
